# Generated by Django 6.1.1 on 2026-09-25 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to='uploads/', verbose_name='Fayl')),
                ('sha256', models.CharField(max_length=64)),
                ('mime', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField(help_text='bytes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to='branches.branch', verbose_name='Filial')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Bir nechta to'g'ri javob"), ('text', 'Yoziladigan javob')], default='single', max_length=10)),
                ('body_format', models.CharField(choices=[('md', 'Markdown'), ('html', 'HTML')], default='md', max_length=4)),
                ('body_src', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('explanation', models.TextField(blank=True, help_text='Izoh (body_format formatida)')),
                ('explanation_html', models.TextField(blank=True, editable=False)),
                ('points', models.PositiveIntegerField(default=1)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_src', models.TextField(blank=True)),
                ('text_html', models.TextField(blank=True, editable=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mediaasset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.question')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='branches.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('description_src', models.TextField(blank=True, verbose_name='Tavsif (markdown)')),
                ('description_html', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan"), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=20)),
                ('time_limit_sec', models.PositiveIntegerField(blank=True, help_text="Bo'sh = cheksiz", null=True, verbose_name='Vaqt chegarasi (soniya)')),
                ('pass_percent', models.PositiveSmallIntegerField(default=60, verbose_name="O'tish foizi")),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('result_visibility', models.CharField(choices=[('none', "Ko'rsatilmaydi"), ('score', 'Faqat ball'), ('full', "To'liq (javoblar bilan)")], default='score', max_length=10)),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text="Bo'sh = cheksiz", null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_tests', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('branch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='branches.branch', verbose_name='Filial')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='content.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.test'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('branch', 'sha256'), name='media_sha256_unique_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('branch', 'slug'), name='subject_slug_unique_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('pass_percent__gte', 0), ('pass_percent__lte', 100)), name='test_pass_percent_range'),
        ),
    ]
