# Generated by Django 6.1.1 on 2026-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text="Faqat o'qituvchi uchun: u ishlay oladigan fanlar (o'z filialidagi).", related_name='teachers', to='content.subject', verbose_name='Fanlar'),
        ),
    ]
