# Generated by Django 6.1.1 on 2026-09-25 10:46

import apps.attempts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=60)),
                ('age', models.PositiveSmallIntegerField()),
                ('access_token', models.CharField(default=apps.attempts.models.new_access_token, editable=False, max_length=64, unique=True)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('finished', 'Yakunlangan'), ('expired', 'Vaqti tugagan')], db_index=True, default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('seed', models.PositiveIntegerField()),
                ('pass_percent', models.PositiveSmallIntegerField()),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(blank=True, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='branches.branch')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='content.test')),
            ],
            options={
                'verbose_name': 'Urinish',
                'verbose_name_plural': 'Urinishlar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('question_snapshot', models.JSONField()),
                ('selected_option_ids', models.JSONField(default=list)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_items', to='content.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['test', 'device_id'], name='attempt_test_device_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('test', 'device_id'), name='one_active_attempt_per_device_test'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'order'), name='attemptitem_unique_order'),
        ),
    ]
